[workspace]
members = [
    "pulldown-html-ext",
    "pulldown-html-ext-cli",
    "pulldown-html-ext-derive"
]
resolver = "2"

[workspace.package]
version = "0.5.0"
edition = "2021"
authors = ["TJ Kells <tjkells@gmail.com>"]
license = "MIT"

