[package]
name = "pulldown-html-ext-derive"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "A derive macro for implementing HTML writers in the pulldown-cmark ecosystem."

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = "2.0.90"

[dev-dependencies]
pulldown-cmark-escape = "0.11.0"
trybuild = "1.0.101"
